apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      
      containers:
        - name: my-nodejs-app
          image: 630787644279.dkr.ecr.us-west-1.amazonaws.com/naz:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: my-registry-key1     
