apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSI2MzA3ODc2NDQyNzkuZGtyLmVjci51cy13ZXN0LTEuYW1hem9uYXdz
LmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsWFZXaERVek5H
UldGdVNUVlNiV2hWVG5wb2VGTkljREJTYldSd1dqTmpkbEl6V201bGFrNVlZek5XUlZZeFdYcGhT
RVozVFZkV2NtRlhPVlJPYTJoS1UwYzFVMk5xV2xCV1YyODFZbXBDTVZadVZtaFJNV3MxV1ZkME1t
RkhXbTFpTVVZMFpGUkNhVmw2VGpKaFdGSXdUVk01UkU5SFozcFdWVm94VjI1b2NWbHNiRzFTVlVw
aFpFUktObGt4VGpKVFYyZDZZekJSTUZSNmJEUmxRemh5VFZoSk5GbHFSa3BUZVhSeVZqRndOV1F6
VG5GT1ZrNUhVakZTTTFVelVscGlSa3A2VjFoR01XRlZWbWxPYmtaVlVsVktkMDVyYUdoak1teHNZ
bFpPVTA1ck1VMWlha0pNVkdwYVUxTlZNREJrUkUxNFlXNUJOVlpGZUc5TlJYUTBZbXRTVFZOVlpF
Sk5WRUpzWld0a1VsZFViRUpSYm14M1RVUlNUMlZyY0hST01EUjRUVVZHYmxOSWJGbFBSMUpFVlRO
c2MxcFhhSEJUUmxvMlZXNUtTR0l4Wkc5T1IyeHRWR3hyTUZSWVZrTmpNMDE1VVZWU2RWVXhWa3RS
ZW14WVRWVm9WMlF5Y0cxVVYyUlZZVEowVWs5V1VtMU9helZZWTBkMGNsZFdaSHBoU0Zrd1ltNVNR
MVF3ZURSU1JVWXpWRVJLU0dSWWFFOVNiWEJYV2tkc2FsTlZPREpXTWxKSVkwaFNOVk51Y0ROT2Jr
azBZVzFHWVdKcmIzWk5SbEl4VGxoQ2FGZEVVakpoUkd4TVRVaE5NR1ZXY0hSVFIwNVlaVVZPY1dG
NlNsSlpWa0pWWkVWa01XRklXbkZPVlRsSlpVZEdjbU15T1UxWmJuQjZZVWhTVTFGdE1YSmlSRUUx
WWxaU1NFNUliREppU0ZKMFZWaG9hMVp0U1RCVlJVNUtWWHBPY2xkRmN6Sk5NRnB3VXpCc1IxTkVh
REJWUXpsUVkyeG9hVlJyY0ZsVmVrSnhZWHBrVTFWSVFraGxiV2hRVkdwV1dtTkdXa1ZUVjBZMVZG
ZG9SVTVZYkZOaU1FWTBTekJLYldGSWNHbFpNbFp0VWpKd1RHSllZekpsYlRGc1VqRk5NV1ZGU1RG
a01VSXlXa2N3ZW1SNlZscFZSbFpRWWtSS2FGWkhlRlpsUjA1S1RXcHNiVlV5ZEc1UFdHUXpUVE5h
Ym1WR1RtRlZSMGx5Vm14U2JtTXllRVphUlVrMVVtMVNkVlZJUW5KaGF6QXhaRWRvYTFSR1RteFRW
VXAzWTFka1NXVnRUWHBrTUVwV1ZtczBkMVJyV1RWTmVtaHdXbTFvUmxwRVFYWlpiWE55VlZoS1Ns
ZFVWVFJMTURWMFRETldOVTFWVFRSU1dHUnlaRWRrV0ZWdVNuaFVWVEY1WkRJMVVtUnRaREprTUho
WFRERmtVV0pXV2t4VE1VcEhaVzVrU1dNd01VZFRia1pKVlRCS1RtRnJlSFpQUjBrMFkwVnNTbFJJ
VG5SVFJsSkdWMGhzTUdKV1l6VlZWekZRWVVkR1dscFlUbGxpYWtKSFZGWkdhMDlWWkRaUFZGb3hW
VEJhVDJWc1ozbGhNa1UxVXpOc1RVNXJVazlUVkdSVVYwUk9iRlJIVGxkbFZVWnlXVlJDTlZSRlNr
MVpiWGN6WTBaT2IxRjZUalpWTVVGM1ZUTm5OVTFxUm5oWFJWSk9Ua2hLYVZvd2NGRmlNalZ6VTIw
NGRrMUhOVk5NTVdScllqQjRSVmRYYUZwa2VteEhVV3RhV1ZKVlVrZFVhemd5VVd0U2RGcFdiRXRQ
UjI5MlVsVktSRlJET1V0WGJsSnZVVlJhU2xSNmJFaFJNRnBEVjBaQ1dVOVhjR3BPUjNBeVUwYzRj
bE50ZUc5bGExcDBWa1pvTUUxVVp6QlZha0paWTBSR1VsRXpjRzVsV0dodldqRktjRTFJUWpKV2Jt
eFJUVEZvVjA0eGFHdGtiRTUwWVhwVmVsbHVXa05pYkU1RFYxWnNWVkpGY3pOVWFtd3hVekJvVTFk
RmRHNVVWekZKVFZkMFNsVlhVbEZXVlVaQ1RUTkNVMDV1WXpGaVYxSk1aVzVhU0ZKcmVITldSWEJ4
V2xOME1VNVZUakJMZVRsSVpIcE5OR0ZYTVRaalYzQnhWVEZHVEZGcmRHNVRVemxxWTJzMWQwNHdX
bEZhTVdST1draGFNMVF3Y0U1U1YxbzFUVzB4UldJelZYcGlibEUwWWxkd1VscHNVVEpUVms1T1Ux
aHNkbVZxYXpSU1ZVWldaRmRTWVZwRk1VTmtSbkJWWXpOV2RsUnNiRWRUTUVacVlWTjBjMkpGV2tS
VmJrWk1UMFY0TmxaR1FYcGhlbWcxV1RKa1RtUkliRTFXVlRnd1ZsUktOVnBYYUVSVmVUa3hWRmRa
ZGs5R1JtRmliVmt4VFZkb1ZscDZNRGxKYVhkcFdrZEdNRmxYZEd4bFUwazJTV3RHVWxKVlNrSlRS
Mnh4VWxWYVdWSXpaRWROVjA1d1kwWmFVRmxYVGtoUFNFWlRZbFZ3ZGxaclNsRlpXR3MwVkVaV1Zt
UnNWVFJWYTA1WFZtcENXV0l3YUROUlZVWkNVMFJTTTFwclJscFRhM1IyVjJ0c2IyUnRUazlSVmta
cVVqSTVTRTlJWkdsVlZXeERVVlZTUTJJd1NtNWhNMFp2WVRKc1NFOVlZM2RSYTBvelVsaGtTVm94
YkV0WFZXeGhVMVZHV0ZaVlVrTlJWVll4VkZWS1JsSlZVa1pTUlU1WFZHdHNUV1JWUmxKVU1FWTFZ
VEk1Vmxvd2JFTlNWV3hDVG5wb2JWRXlTa3hQUlZKd1RrWmFVRTB4YUZST2JVWnVVekZuTTAxc1dq
VlBTSEJzVWtoQ1VWUXhaRTVPTUhoTVZHeENVMXA2VmpOalZGcE9URE5TUjFwRmRFOVNibXh2VFRK
S1RHUklaRFJqVld3eFN6TlNjRlpJYUZGT01HaHVaRWMxUms1NlNrWlZSVVU1U1dsM2FXUnRWbmxq
TW14MlltbEpOa2xxU1dsTVEwb3daVmhDYkVscWIybFNSVVpWVVZZNVRGSldhMmxNUTBwc1pVaENj
R050UmpCaFZ6bDFTV3B2ZUU1cVp6Tk5ha2w2VGxSck1XWlJQVDA9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson    